### PR TITLE
make api more REST conform and secure workflow registration

### PR DESCRIPTION
**Pull request by michaelmattig**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
Nothing to complain about so far. Just one question, do the examples of WMS and WFS still work with the added authentication and authorization step for workflows?

**Comment by michaelmattig** [comment]
> 
> 
> Nothing to complain about so far. Just one question, do the examples of WMS and WFS still work with the added authentication and authorization step for workflows?

good point, it doesn't work and is missed by the CI. Should I change the example to try to register (might fail when example is opened second time) and then login or should I pass the workflow directly (only supported by WFS I think)?

**Comment by ChristianBeilschmidt** [comment]
> > Nothing to complain about so far. Just one question, do the examples of WMS and WFS still work with the added authentication and authorization step for workflows?
> 
> good point, it doesn't work and is missed by the CI. Should I change the example to try to register (might fail when example is opened second time) and then login or should I pass the workflow directly (only supported by WFS I think)?

Yes, try to register and don't crash, but output _already registered_ to the console. This way, the example should be working again.

**Comment by michaelmattig** [comment]
> 
> 
> > > Nothing to complain about so far. Just one question, do the examples of WMS and WFS still work with the added authentication and authorization step for workflows?
> > 
> > 
> > good point, it doesn't work and is missed by the CI. Should I change the example to try to register (might fail when example is opened second time) and then login or should I pass the workflow directly (only supported by WFS I think)?
> 
> Yes, try to register and don't crash, but output _already registered_ to the console. This way, the example should be working again.

it works now but doesn't log yet. For this to work I still need more detailed error reporting. Right now it only outputs a message but we need to output the error kind/code to the client to correctly detect that the error is in fact that the user already exists and there is no other error.

**Pull request merged**
