### PR TITLE
update rust version and clippy lints

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**
- [x] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[Update Backend](https://trello.com/c/ObBWTN74/1157-update-backend)

**Review by michaelmattig — APPROVED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Comment by michaelmattig** [comment]
bors retry

**Comment by michaelmattig** [comment]
bors retry

**Comment by michaelmattig** [comment]
bors retry

**Pull request merged**
