### PR TITLE
Hide GFBio collections item

### PR DESCRIPTION
**Pull request by dbrandenstein**
- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

### CODE REVIEW

**Comment by dbrandenstein** [comment]
[GFBio Collections Eintrag ausblenden](https://trello.com/c/S1HeD38z/1275-gfbio-collections-eintrag-ausblenden)

**Comment by michaelmattig** [comment]
[GFBio Collections Eintrag ausblenden](https://trello.com/c/S1HeD38z/1275-gfbio-collections-eintrag-ausblenden)

**Comment by michaelmattig** [comment]
bors merge

**Comment by michaelmattig** [comment]
bors merge

**Comment by michaelmattig** [comment]
bors merge

**Pull request merged**
