### PR TITLE
setup bors workflow

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by ChristianBeilschmidt** [comment]
[bors einrichten](https://trello.com/c/FLpvUPOo/452-bors-einrichten)

**Comment by michaelmattig** [comment]
bors merge

**Review by michaelmattig — DISMISSED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Review by michaelmattig — DISMISSED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by ChristianBeilschmidt** [comment]
bors try-

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by ChristianBeilschmidt** [comment]
bors try

**Comment by michaelmattig** [comment]
bors merge

**Review by michaelmattig — APPROVED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Pull request merged**
