### PR TITLE
use methods from gdal crate, remove helpers

### PR DESCRIPTION
**Pull request by jdroenner**

### CODE REVIEW

**Comment by jdroenner** [comment]
[update gdal source to use gdal crate methods for masks](https://trello.com/c/2D6mB1Jy/980-update-gdal-source-to-use-gdal-crate-methods-for-masks)

**Comment by michaelmattig** [comment]
bors merge

**Comment by michaelmattig** [comment]
bors retry

**Comment by michaelmattig** [comment]
bors retry

**Pull request merged**
