### PR TITLE
set ci to latest nightly

### PR DESCRIPTION
**Pull request by jdroenner**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
https://github.com/rust-lang/packed_simd/issues/288

**Comment by ChristianBeilschmidt** [comment]
Let's hope for https://github.com/rust-lang/packed_simd/issues/298

**Comment by jdroenner** [comment]
arrow needs a new release to get this working. the packed_simd crate was replaced here: https://github.com/apache/arrow/commit/dcc86f47b2075dc23e2f26a05c20d719acb692a8

**Comment by ChristianBeilschmidt** [comment]
Ok, let's hope they will release a patch version soon.

**Comment by ChristianBeilschmidt** [comment]
cf. https://github.com/geo-engine/geoengine/pull/52

**Pull request closed without merging**
