### PR TITLE
Ml training

### PR DESCRIPTION
**Pull request by michaelmattig**
- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

### CODE REVIEW

**Comment by michaelmattig** [comment]
[XGBoost-Operator ausprobieren](https://trello.com/c/2y5x739k/1426-xgboost-operator-ausprobieren)

**Comment by michaelmattig** [comment]
[XGBoost-Operator implementieren](https://trello.com/c/QoxXOMwb/1048-xgboost-operator-implementieren)

**Comment by michaelmattig** [comment]
[XGBoost-Operator implementieren](https://trello.com/c/QoxXOMwb/1048-xgboost-operator-implementieren)

**Comment by michaelmattig** [comment]
[Integration von Marcus Machine Learning Training](https://trello.com/c/eH9P93XD/1454-integration-von-marcus-machine-learning-training)

**Review by jdroenner — APPROVED** [review]

**Pull request merged**
