### PR TITLE
more fixing on over/under colors in API

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**
- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[Deploybare Version des EBV-Analyzers erstellen](https://trello.com/c/rCZOfj4w/1169-deploybare-version-des-ebv-analyzers-erstellen)

**Review by michaelmattig — APPROVED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Comment by michaelmattig** [comment]
bors merge

**Comment by michaelmattig** [comment]
bors retry

**Pull request merged**
