### PR TITLE
fix DateTime SQL

### PR DESCRIPTION
**Pull request by michaelmattig**

### CODE REVIEW

**Comment by michaelmattig** [comment]
[In der Pro-Version gibt die Session-API falsche Datumswerte aus](https://trello.com/c/M6RmwixO/891-in-der-pro-version-gibt-die-session-api-falsche-datumswerte-aus)

**Comment by ChristianBeilschmidt** [comment]
Can you add a test that verifies this fix? It is always concerning if we change behavior and no tests need to be adjusted :smile:.

**Comment by michaelmattig** [comment]
> Can you add a test that verifies this fix? It is always concerning if we change behavior and no tests need to be adjusted 😄.

I just delegate the method and the actual implementation is tested in the postgres_types crate. Doesn't this suffice?

**Comment by michaelmattig** [comment]
> Can you add a test that verifies this fix? It is always concerning if we change behavior and no tests need to be adjusted 😄.

unfortunately, I can't. The config for the postgres isn't accessible in the datatypes crate. I guess it's ok though because I only delegate the method to the implementation in postgres_types.

**Comment by ChristianBeilschmidt** [comment]
From Slack: Test the functionality in the services crate.

**Comment by michaelmattig** [comment]
I indirectly test it now as part of the method where we first noticed the error: 773c15bffb399b731d74d5dff5eea73e6c5d3f2b

**Review by ChristianBeilschmidt — APPROVED** [review]

**Comment by ChristianBeilschmidt** [comment]
bors merge

**Pull request merged**
