### PR TITLE
fix new nightly and apply lints

### PR DESCRIPTION
**Pull request by ChristianBeilschmidt**

### CODE REVIEW

**Comment by ChristianBeilschmidt** [comment]
[Update Backend](https://trello.com/c/6z4BkFl8/576-update-backend)

**Review by michaelmattig — DISMISSED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Review by michaelmattig — APPROVED** [review]

**Comment by michaelmattig** [comment]
boris merge

**Comment by michaelmattig** [comment]
bors merge

**Pull request merged**
