### PR TITLE
put xgboost behind a feature

### PR DESCRIPTION
**Pull request by jdroenner**
- [ ] I added an entry to [`CHANGELOG.md`](CHANGELOG.md) if knowledge of this change could be valuable to users.

---

Here is a brief summary of what I did:

<TEXT>

### CODE REVIEW

**Comment by jdroenner** [comment]
[XGBoost feature gate](https://trello.com/c/gOY3rcY2/1138-xgboost-feature-gate)

**Review by michaelmattig — APPROVED** [review]

**Comment by michaelmattig** [comment]
bors merge

**Comment by michaelmattig** [comment]
bors retry

**Comment by michaelmattig** [comment]
bors retry

**Pull request merged**
